spring:
  profiles:
    active: sly

---
spring:
  profiles: sly
  datasource:
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13579abc
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-handlers-package: com.cskaoyan.cskaoyanmall.handler

server:
  servlet:
    context-path: /
  port: 80


---
spring:
  profiles: tangxian
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
server:
  servlet:
    context-path: /
  port: 80

---
spring:
  profiles: xxx
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxx
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
server:
  servlet:
    context-path: /
  port: 80










## The following are old configurations: ##


#server:
#  servlet:
#    context-path: /admin
#  port: 80
#
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cskaoyanmall?useSSL=false
#    username: root
#    password: 123456
#  profiles:
#    active: alpha
#
#---
#spring:
#  profiles: alpha
#
#db:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
#  username: root
#  password: 123456
#
#---
#spring:
#  profiles: didi
#
#db:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
#  username: root
#  password: 123456
#
#---
#spring:
#  profiles: cly
#
#db:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
#  username: root
#  password: 123456
#
#---
#spring:
#  profiles: zsw
#
#db:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
#  username: root
#  password: mysql520520
