# Common Configurations
spring:
  profiles:
#    active: chris
    active: donghao

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


server:
  servlet:
    context-path: /admin
  port: 80
#---
#spring:
#  profiles: zck
#  datasource:
#    url: jdbc:mysql://localhost:3306/malldemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone= Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 121212
#    type: com.alibaba.druid.pool.DruidDataSource

---
spring:
  profiles: chris
  datasource:
    # if not specified, use HikariPool by default
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
---
spring:
  profiles: weihao
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall
---
spring:
  profiles: donghao
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useSSL=false&characterEncoding=UTF-8